### ISSUE TITLE
Forward motion

### ISSUE THREAD

**Issue by menandro** [VLOGroup/surface-area-regularization#1]
I tried using this for two images where the camera moves towards the z-axis (forward/backward). Does this method work in those cases?

**Comment by gottfriedm** [comment]
Pure forward motion is a degenerate case for any stereo algorithm. However, if it is a real camera there is typically a little bit of baseline, so it might work nonetheless.
I might have a sanity check in the code that enforces a 3d point must be seen under a minimum angle (=minimum baseline), this would fail in case of forward motion.

**Comment by menandro** [comment]
I worked around it by simply scaling the translation vector. Thanks!
